FROM python:3.8-slim-buster

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /home/dedalus

COPY requirements.txt /home/dedalus/requirements.txt

RUN apt-get update && pip install --upgrade pip && pip install -r requirements.txt

# copy project
COPY . /home/dedalus