version: "3.7"

services:
  web:
    build:
      context: .
    env_file:
      - .env.prod
    restart: on-failure
    command: gunicorn StatisticsTgBot.wsgi:application --bind 0.0.0.0:8000
    volumes:
    - static_volume:/home/dedalus/static
    - media_volume:/home/dedalus/uploads
    expose:
      - 8000
    depends_on:
      - db
  bot_group:
    build:
      context: .
      dockerfile: Dockerfile_bot_group
    command: python manage.py bot_group
    restart: on-failure
    env_file:
      - .env
    depends_on:
      - db
  bot_tp:
    build:
      context: .
      dockerfile: Dockerfile_bot_tp
    command: python manage.py bot
    restart: on-failure
    env_file:
      - .env
    depends_on:
      - db
      - redis
  db:
    image: postgres:12.6
    ports:
    - "5432:5432"
    env_file:
      - .env.prod.db
    restart: always
    volumes:
    - postgres_data:/var/lib/postgresql/data/
  redis:
    image: redis:latest
    restart: on-failure
    volumes:
    - redis_data:/data
  nginx:
    build: ./nginx
    ports:
    - "80:80"
    volumes:
    - static_volume:/home/dedalus/static
    - media_volume:/home/dedalus/uploads
    depends_on:
      - web

volumes:
  postgres_data:
  redis_data:
  static_volume:
  media_volume:
