# Generated by Django 3.1.7 on 2021-04-21 18:15

import TgAdmin.models
from django.db import migrations, models
import django.db.models.deletion
import mdeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=255, unique=True, verbose_name='Id группы')),
                ('name', models.CharField(max_length=255, verbose_name='Название группы')),
                ('url_link', models.CharField(choices=[('tp', 'https://t.me/test_2_dedalus_bot')], default='tp', help_text='Выбрать ссылку для перехода пользователя, после нажатия на клавишу "согласен"', max_length=255, verbose_name='Ссылка на тп/магазин')),
                ('language', models.CharField(choices=[('ru', 'Русский'), ('en', 'English')], default='ru', max_length=2, verbose_name='Язык')),
                ('url_chat', models.URLField(blank=True, help_text='По умолчанию добавляется ссылка чата. Если измените ссылку-приглашение, то здесь необходимо изменить ссылку', max_length=255, null=True, verbose_name='Ссылка на чат')),
            ],
            options={
                'verbose_name': 'Название чата',
                'verbose_name_plural': 'Названия чатов',
            },
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_before_btn', mdeditor.fields.MDTextField(default='Текст для приветствия новых пользователей в чате на русском языке', verbose_name='Текст рядом с кнопками (русский)')),
                ('text_before_btn_en', mdeditor.fields.MDTextField(default='Текст для приветствия новых пользователей в чате на английском языке', verbose_name='Текст рядом с кнопками (english)')),
                ('image', models.ImageField(blank=True, null=True, upload_to=TgAdmin.models.user_directory_path, verbose_name='Фотография для текста')),
                ('btn1', models.CharField(default='Согласен', max_length=255, verbose_name='Кнопка 1 (русский)')),
                ('btn1_en', models.CharField(default='Agree', max_length=255, verbose_name='Кнопка 1 (english)')),
                ('btn2', models.CharField(default='Отклонить', max_length=255, verbose_name='Кнопка 2 (русский)')),
                ('btn2_en', models.CharField(default='Reject', max_length=255, verbose_name='Кнопка 2 (english)')),
                ('faq', models.TextField(default='\n    Здесь будут ответы на часто задаваевые вопросы!\n    Сейчас введите команду "/support", чтобы задать вопрос в техподдержку.\n    ', verbose_name='FAQ для техподдержки')),
                ('faq_en', models.TextField(default='\n    Here are the answers to frequently asked questions!\n    Now enter the command "/support" to ask a question to technical support.\n    ', verbose_name='FAQ english для техподдержки')),
                ('text_mailing', mdeditor.fields.MDTextField(default='Текст для рассылки', verbose_name='Текс для рассылки в техподдержке')),
            ],
            options={
                'verbose_name': 'Данные для изменения',
            },
        ),
        migrations.CreateModel(
            name='TempDataBtn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_message', models.CharField(max_length=255, verbose_name='ID сообщения в техподдержке')),
                ('id_user', models.CharField(max_length=255, unique=True, verbose_name='ID пользователя')),
            ],
            options={
                'verbose_name': 'Временные данные для обработчика',
                'verbose_name_plural': 'Временные данные для обработчика',
            },
        ),
        migrations.CreateModel(
            name='TempDataSupport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_message', models.CharField(max_length=255, verbose_name='ID сообщения в техподдержке')),
                ('id_user', models.CharField(max_length=255, unique=True, verbose_name='ID пользователя')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст сообщения')),
            ],
            options={
                'verbose_name': 'Временные данные техподдержки',
                'verbose_name_plural': 'Временные данные техподдержки',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iduser', models.CharField(db_index=True, max_length=255, verbose_name='ID пользователя')),
                ('username', models.CharField(blank=True, max_length=255, null=True, verbose_name='Username пользователя')),
                ('fullname', models.CharField(blank=True, max_length=255, null=True, verbose_name='Полное имя пользователя')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления пользователя')),
                ('state', models.CharField(choices=[('1', 'Бездействие'), ('2', 'Согласен'), ('3', 'Не согласен'), ('4', 'Согласен+тп'), ('5', 'Из-вне')], db_index=True, default='1', max_length=1)),
                ('is_banned', models.BooleanField(default=False)),
                ('language', models.CharField(choices=[('no', None), ('ru', 'Русский'), ('en', 'English')], default='no', max_length=2)),
                ('message_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Id сообщения при вступлении в группу')),
                ('chat_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='TgAdmin.chat')),
            ],
            options={
                'verbose_name': 'Пользователь телеграма',
                'verbose_name_plural': 'Пользователи телеграма',
                'ordering': ['-date_joined'],
                'unique_together': {('iduser', 'chat_id')},
            },
        ),
    ]
