# Generated by Django 3.1.7 on 2021-09-26 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TgAdmin', '0002_auto_20210515_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='id_admin',
            field=models.CharField(default='', help_text='ID пользователя, кто будет добавлять чаты в БД', max_length=100, verbose_name='ID пользователя'),
        ),
    ]
